### ISSUE TITLE
安装过程失败

### ISSUE THREAD

**Issue by hellohoxiang** [welliamcao/VManagePlatform#39]
centos6.10 python2.7.15  pip 19.3.1
以上环境系统在 pip install -r requirements.txt 时出错。
请问是项目不支持centos6了吗？还是django==1.8.17不支持6。其它情况。

`[root@localhost VManagePlatform]# pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting django==1.8.17
  Downloading https://files.pythonhosted.org/packages/0a/df/5ac011953ca547a1fb602e3e5c96a4cb94f7333e8f27b13d51dca880a110/Django-1.8.17-py2.py3-none-any.whl (6.2MB)
     |█████▊                          | 1.1MB 6.5kB/s eta 0:13:03ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_vendor/urllib3/response.py", line 439, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
[root@localhost VManagePlatform]# cat /usr/local/lib/python2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/cli/base_command.py
"""Base Command class, and related routines"""`

**Comment by welliamcao** [comment]
支持centos6，你前面的安装步骤有没有漏掉？

**Comment by hellohoxiang** [comment]
按照文档安装的。centos6.10 python2.7.15 pip 19.3.1  再次安装，经过检查，主要是以下情况：
pip install -r requirements.txt  原因如下
1、pip install过程没有加速，失败
处理：
Linux下，修改 ~/.pip/pip.conf 
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
[install]
trusted-host = https://pypi.tuna.tsinghua.edu.cn
2、libvirt-python没有指定版本，默认安装5.7.0（centos6.10 python2.7.15 pip 19.3.1  可能不支持该版本版本）
处理:pip install   libvirt-python==3.8.0 
3.8.0的版本目前还不知道能不能用，安装还没有完成
